### ISSUE TITLE
error loading SVG files

### ISSUE THREAD

**Issue by hex705** [amandaghassaei/OrigamiSimulator#1]
HI,

Amazing work!  

While running downloaded simulator in Chrome, OSX (10.10.5) i get this error on launch

Error loading SVG assets/Tessellations/huffmanWaterbomb.svg : [object ProgressEvent]

I do not get the error in firefox.

s

**Comment by amandaghassaei** [comment]
just seeing this now, is this still an issue?

**Comment by glvn-xyz** [comment]
Hi Amanda. I was trying to reach you via e-mail but had no reply. I would really love to discuss one project with you. I just need your answer and idea on that. Sorry for spamming here, I will delete this message later.

**Comment by edemaine** [comment]
Closing this as inactive.  @hex705, if you're still having trouble, feel free to reopen the issue.
