### ISSUE TITLE
Link to paper

### ISSUE THREAD

**Issue by edemaine** [amandaghassaei/OrigamiSimulator#11]
We should link to [our 7OSME paper about the simulator](http://erikdemaine.org/papers/OrigamiSimulator_Origami7/) in the About page.

**Comment by amandaghassaei** [comment]
it's in the about modal at the very bottom - could maybe bit a bit easier to find.  Fine to change the link to your nice abstract too, I'm not picky.

**Comment by edemaine** [comment]
Oops, I missed that; thanks!  I was thinking it would fit with the other two papers cited, so I'll move it.
