### ISSUE TITLE
Error loading SVG assets

### ISSUE THREAD

**Issue by swipswaps** [amandaghassaei/OrigamiSimulator#17]
I get this in firefox on Linux: "Error loading SVG assets"
//re: just seeing this now, is this still an issue?

_Originally posted by @amandaghassaei in https://github.com/amandaghassaei/OrigamiSimulator/issues/1#issuecomment-366298261_

**Comment by edemaine** [comment]
Are you seeing this on https://origamisimulator.org/ or in a locally downloaded copy?

**Comment by dskeithbuck** [comment]
I'm seeing it in a locally downloaded copy.

**Comment by edemaine** [comment]
Origami Simulator won't run on a `file:` URL.  You need to serve the pages via a local server, e.g. `python2 -m SimpleHTTPServer` or `python3 -m http.server`, and then connect to `http://localhost`.
