### ISSUE TITLE
Cannot Export as OBJ / STL

### ISSUE THREAD

**Issue by dskeithbuck** [amandaghassaei/OrigamiSimulator#18]
## To Reproduce

1. Go to [http://apps.amandaghassaei.com/OrigamiSimulator/](http://apps.amandaghassaei.com/OrigamiSimulator/)
2. Load the Paper Crane: `Examples > Origami > Crane (3D)`
3. `File > Save Simulation as OBJ...`
4. Use the Default Settings and press `Save`.
> BUG: Nothing happens, no download initiates.

If you open the Console, you'll see this error:

![image](https://user-images.githubusercontent.com/39964241/69179652-b8e16800-0ac0-11ea-9be7-014c1a2f4077.png)

```
saveSTL.js:128 Uncaught TypeError: Cannot read property 'length' of undefined
    at saveOBJ (saveSTL.js:128)
    at controls.js:160
    at HTMLButtonElement.<anonymous> (controls.js:753)
    at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)
```
This is the section of code it's referencing:

![image](https://user-images.githubusercontent.com/39964241/69179693-c8f94780-0ac0-11ea-8c2e-81ed544798cb.png)

`    for (var i=0;i<flatGeo.vertices.length;i++){`

Thanks,

Donovan

**Comment by edemaine** [comment]
Thanks for the report! Actually, this bug was fixed already: the version deployed on https://origamisimulator.org/ works fine.

@amandaghassaei should either decommission or update the version on http://apps.amandaghassaei.com/OrigamiSimulator/.

**Comment by dskeithbuck** [comment]
I didn't know about https://origamisimulator.org/ thanks for the heads up!
