### ISSUE TITLE
C'ant inport simple SVG!

### ISSUE THREAD

**Issue by Molenbart** [amandaghassaei/OrigamiSimulator#3]
Beautiful app. Good job!
I can hardly wait to try it out with my own designs.

I am trying to import a simple file created with Inkscape before I try the real job. I always get the message "Grouped elements found in SVG, they are currently being ignored by the app. Remove all elements before importing them." I'm sure there are no groups.
Please, can you take a look and tell me what I do wrong.

Thanks in advance,
Bart

**Comment by edemaine** [comment]
@Molenbart If you could send the SVG file you're having trouble with, I'd be happy to take a look at it.  You could post it as a Gist, for example.
