### ISSUE TITLE
Simulation Angle Export/ FOLD with multiple frames export

### ISSUE THREAD

**Issue by jtpelster** [amandaghassaei/OrigamiSimulator#36]
I have completed code to export the current simulation angles for each edge in a custom edges_crease_angle_os: field and added an option to simulate multiple fold percents from one percent to another by a step size as frames and add them to a FOLD file in the FOLD format.
This introduces another file menu item.
Is it appropriate to open a pull request? I feel like these changes are in line with the project, but could see it also not fitting.

**Comment by edemaine** [comment]
Yes, feel free to open a pull request!  I can't say without looking at it whether it will be merged, but happy to take a look.
