### ISSUE TITLE
Fold percentage opacity vs rgba

### ISSUE THREAD

**Issue by forresto** [amandaghassaei/OrigamiSimulator#51]
In the design tips, I thought that fold percentage via opacity meant define stroke colors as RGBA. But I guess that should actually be `opacity` on the strokes? It might be good to support both (Cuttle can do RGBA but not opacity so far.)

.cuttle.svg: https://cuttle.xyz/@forresto/folds-with-rgba-AJritDsxIJkN

<img width="527" alt="image" src="https://user-images.githubusercontent.com/395307/146078736-01880411-96ca-4487-bfac-fc128e43f58f.png">

**Comment by edemaine** [comment]
Good idea. This should not be hard to implement.

**Comment by edemaine** [comment]
But [it is standard for SVG 2](https://www.w3.org/TR/2013/WD-SVG2-20130409/color.html) so I think it makes sense to support eventually. Probably good to avoid it in your software for now, though. 🙂
