### ISSUE TITLE
Folding order

### ISSUE THREAD

**Issue by rafeekwassef** [amandaghassaei/OrigamiSimulator#56]
Hi,

Is there any way to control the folding steps, I believe how the folding process works in orders could help for many use cases.

Regards,

**Comment by edemaine** [comment]
No, sadly. Origami simulator computes a folding motion where every crease moves at once. Generating folding step sequences is an area of research that is still in its infancy. See [this paper](https://dl.acm.org/doi/10.1145/2503385.2503407) or [this paper](http://erikdemaine.org/papers/Matter_Robotica/).
