### ISSUE TITLE
Error when saving to OBJ

### ISSUE THREAD

**Issue by AlexanderDudek** [amandaghassaei/OrigamiSimulator#8]
When trying to save the file to OBJ on Chrome, macOS 10.14.4 the following error appears in the console:

Uncaught TypeError: Cannot read property 'length' of undefined
    at saveOBJ (saveSTL.js:128)
    at controls.js:160
    at HTMLButtonElement.<anonymous> (controls.js:753)
    at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)

(Saving to STL works correctly)

**Comment by freestraws** [comment]
The error is because of the change with uv coords, I was the one to originally request the change, but it wasn't implemented 100% correctly, and have since made a pull request that fixes it, #7 , but haven't received any response (even after emailing the author).

**Comment by edemaine** [comment]
@AlexanderDudek This bug has been fixed on master, thanks to @freestraws's PR #7. It will appear in a public version of the webapp shortly. I'll update and close the issue then.

**Comment by edemaine** [comment]
New version is now live at http://origamisimulator.org/! Let us know if you have any issues.
